export interface FixedBookOption {
  id: string;
  title: string;
  price: number;
  supplier: string;
}

export const fixedBookOptionsByClass: Record<string, FixedBookOption[]> = {
  '10th': [
    { id: 'english-kumarbharati-text', title: 'English Kumarbharati - Text book', price: 99, supplier: 'Govt.' },
    { id: 'english-kumarbharati-workbook', title: 'English Kumarbharati - Workbook', price: 250, supplier: 'Navneet' },
    { id: 'english-hl-grammar', title: 'English HL Grammer', price: 150, supplier: 'Navneet' },
    { id: 'english-writing-skill', title: 'English Writing Skill', price: 120, supplier: 'Navneet' },
    { id: 'maths-part1-text', title: 'Maths Part I - Textbook', price: 113, supplier: 'Govt.' },
    { id: 'maths-part1-workbook', title: 'Maths Part I - Workbook', price: 90, supplier: 'Navneet' },
    { id: 'maths-part2-text', title: 'Maths Part II - Textbook', price: 108, supplier: 'Govt.' },
    { id: 'maths-part2-workbook', title: 'Maths Part II - Workbook', price: 115, supplier: 'Navneet' },
    { id: 'maths-practical', title: 'Maths 1 and 2 Practical Book', price: 85, supplier: 'Vikas' },
    { id: 'history-textbook', title: 'History and Political Science Textbook', price: 76, supplier: 'Govt.' },
    { id: 'history-workbook', title: 'History and Political Science Workbook', price: 150, supplier: 'Navneet' },
    { id: 'geography-textbook', title: 'Geography Textbook', price: 58, supplier: 'Govt.' },
    { id: 'geography-workbook', title: 'Geography Workbook', price: 125, supplier: 'Navneet' },
    { id: 'geography-mapbook', title: 'Geography MAPBOOK & Activity Book (Vikas Finding Locations)', price: 75, supplier: 'Navneet' },
    { id: 'hindi-textbook', title: 'Hindi Lokbharati Textbook', price: 78, supplier: 'Govt.' },
    { id: 'hindi-workbook', title: 'Hindi Lokbharati Workbook', price: 220, supplier: 'Navneet' },
    { id: 'hindi-grammar', title: 'Hindi Grammer', price: 75, supplier: 'Vikas' },
    { id: 'marathi-textbook', title: 'Marathi Akshar Bharati Textbook', price: 64, supplier: 'Govt.' },
    { id: 'marathi-workbook', title: 'Marathi Akshar Bharati Workbook', price: 170, supplier: 'Navneet' },
    { id: 'marathi-grammar', title: 'Marathi Grammer', price: 60, supplier: 'Navneet' },
    { id: 'science-part1', title: 'Science & Technology Part - 1 Textbook', price: 103, supplier: 'Govt.' },
    { id: 'science-part2', title: 'Science & Technology Part - 2 Textbook', price: 88, supplier: 'Govt.' },
    { id: 'defence-studies', title: 'Defence Studies', price: 75, supplier: 'Navneet' },
    { id: 'water-security', title: 'Water Security', price: 140, supplier: 'Navneet' },
    { id: 'health-pe', title: 'Health and Physical Education', price: 90, supplier: 'Navneet' },
    { id: 'notebook-long', title: 'Single line 200 pg Long notebook - 14 (long book)', price: 1120, supplier: 'Navneet' },
    { id: 'diary-id-card', title: 'Diary & I Card', price: 170, supplier: 'Navneet' },
  ],
  '9th': [
    { id: '9-eng-text', title: 'English Kumarbhrati - Text book', price: 88, supplier: 'Govt.' },
    { id: '9-eng-work', title: 'English Kumarbhrati - Workbook', price: 170, supplier: 'Navneet' },
    { id: '9-eng-gram', title: 'English HL Grammer', price: 110, supplier: 'Navneet' },
    { id: '9-eng-write', title: 'English Writing skill', price: 115, supplier: 'Navneet' },
    { id: '9-math1-text', title: 'Maths Part I - Textbook', price: 91, supplier: 'Govt.' },
    { id: '9-math1-work', title: 'Maths Part I - Workbook', price: 100, supplier: 'Navneet' },
    { id: '9-math2-text', title: 'Maths Part II - Textbook', price: 86, supplier: 'Govt.' },
    { id: '9-math2-work', title: 'Maths Part II - Workbook', price: 115, supplier: 'Navneet' },
    { id: '9-math-prac', title: 'Maths practical Book', price: 75, supplier: 'Vikas' },
    { id: '9-hist-text', title: 'History and Poitical Scinece Textbook', price: 74, supplier: 'Govt.' },
    { id: '9-hist-work', title: 'History and Plitical Scinece Workbook', price: 130, supplier: 'Navneet' },
    { id: '9-geo-text', title: 'Geography Textbook', price: 78, supplier: 'Govt.' },
    { id: '9-geo-work', title: 'Geography Workbook', price: 125, supplier: 'Navneet' },
    { id: '9-geo-map', title: 'Geography MAPBOOK & Activity Book (Vikas Finding Locations)', price: 65, supplier: 'Navneet' },
    { id: '9-hin-text', title: 'Hindi Lokbharati Textbook', price: 69, supplier: 'Govt.' },
    { id: '9-hin-work', title: 'Hindi Lokbharati workbook', price: 190, supplier: 'Navneet' },
    { id: '9-hin-gram', title: 'Hindi Lokbharati Vavsay (Grammer Book) (Workbook)', price: 75, supplier: 'Navneet' },
    { id: '9-mar-text', title: 'Marathi Akshar bharati textbook', price: 63, supplier: 'Govt.' },
    { id: '9-mar-work', title: 'Marathi Akshar bharati workbook', price: 150, supplier: 'Navneet' },
    { id: '9-mar-gram', title: 'Marathi Grammer', price: 70, supplier: 'Vikas' },
    { id: '9-sci-text', title: 'Science & Technology Textbook', price: 146, supplier: 'Govt.' },
    { id: '9-sci-prac', title: 'Science & Technology Practial book', price: 75, supplier: 'Navneet' },
    { id: '9-def', title: 'Defence Studies', price: 90, supplier: 'Navneet' },
    { id: '9-water', title: 'Water Security', price: 140, supplier: 'Navneet' },
    { id: '9-health', title: 'Heatlh and Physical Education', price: 90, supplier: 'Navneet' },
    { id: '9-note', title: 'Single line 200 pg Long notebook - 11 (long book)', price: 880, supplier: 'Navneet' },
    { id: '9-diary', title: 'Diary & I Card', price: 175, supplier: 'Navneet' },
  ],
  '8th': [
    { id: '8-bal', title: 'BalBharati', price: 71, supplier: 'Govt. Text Book' },
    { id: '8-math', title: 'Mathematics', price: 74, supplier: 'Govt. Text Book' },
    { id: '8-sci', title: 'Gen. Science', price: 89, supplier: 'Govt. Text Book' },
    { id: '8-hist', title: 'History', price: 62, supplier: 'Govt. Text Book' },
    { id: '8-geo', title: 'Geography', price: 56, supplier: 'Govt. Text Book' },
    { id: '8-hin', title: 'Hindi', price: 48, supplier: 'Govt. Text Book' },
    { id: '8-mar', title: 'Marathi', price: 48, supplier: 'Govt. Text Book' },
    { id: '8-eng-work', title: 'English workbook', price: 165, supplier: 'Navneet' },
    { id: '8-math-work', title: 'Maths workbook', price: 180, supplier: 'Navneet' },
    { id: '8-hist-work', title: 'History and civics workbook', price: 180, supplier: 'Navneet' },
    { id: '8-geo-work', title: 'Geography workbook', price: 110, supplier: 'Navneet' },
    { id: '8-hin-work', title: 'Hindi sulabh workbook', price: 140, supplier: 'Navneet' },
    { id: '8-mar-work', title: 'Marathi sulabh workbook', price: 100, supplier: 'Navneet' },
    { id: '8-sci-work', title: 'General science workbook', price: 260, supplier: 'Navneet' },
    { id: '8-hin-gram', title: 'Hindi grammer', price: 75, supplier: 'Navneet' },
    { id: '8-mar-gram', title: 'Marathi grammer', price: 70, supplier: 'Navneet' },
    { id: '8-eng-gram', title: 'Englsih Vikas golden grammer', price: 170, supplier: 'Vikas' },
    { id: '8-sci-prac', title: 'Navneet general science practical book', price: 70, supplier: 'Navneet' },
    { id: '8-eng-write', title: 'English writing skills', price: 80, supplier: 'Navneet' },
    { id: '8-note', title: 'Single line 200 pg Long notebook - 11(A4 size)', price: 880, supplier: 'Navneet' },
    { id: '8-draw', title: '4A Jumbo Drawing book - Brown Colour', price: 55, supplier: 'Navneet' },
    { id: '8-diary', title: 'Diary & I Card', price: 170, supplier: 'Navneet' },
  ],
  '7th': [
    { id: '7-bal', title: 'BalBharati', price: 71, supplier: 'Govt. Books' },
    { id: '7-math', title: 'Mathematics', price: 66, supplier: 'Govt. Books' },
    { id: '7-sci', title: 'Gen. Science', price: 90, supplier: 'Govt. Books' },
    { id: '7-hist', title: 'History', price: 62, supplier: 'Govt. Books' },
    { id: '7-geo', title: 'Geography', price: 58, supplier: 'Govt. Books' },
    { id: '7-hin', title: 'Hindi', price: 43, supplier: 'Govt. Books' },
    { id: '7-mar', title: 'Marathi', price: 48, supplier: 'Govt. Books' },
    { id: '7-eng-work', title: 'English workbook', price: 125, supplier: 'Navneet' },
    { id: '7-math-work', title: 'Maths workbook', price: 115, supplier: 'Navneet' },
    { id: '7-hist-work', title: 'History and civics workbook', price: 130, supplier: 'Navneet' },
    { id: '7-geo-work', title: 'Geography workbook', price: 105, supplier: 'Navneet' },
    { id: '7-hin-work', title: 'Hindi sulabh workbook', price: 130, supplier: 'Navneet' },
    { id: '7-mar-work', title: 'Marathi sulubh workbook', price: 110, supplier: 'Navneet' },
    { id: '7-sci-work', title: 'General science workbook', price: 185, supplier: 'Navneet' },
    { id: '7-hin-gram', title: 'Hindi grammer Book', price: 75, supplier: 'Navneet' },
    { id: '7-mar-gram', title: 'Marathi grammer Book', price: 70, supplier: 'Navneet' },
    { id: '7-eng-gram', title: 'English golden grammer', price: 110, supplier: 'Vikas' },
    { id: '7-comp', title: 'Computer - Information technology', price: 100, supplier: 'Navneet' },
    { id: '7-moral', title: 'Moral Education', price: 60, supplier: 'Navneet' },
    { id: '7-gk', title: 'Navneet general knowledge', price: 110, supplier: 'Navneet' },
    { id: '7-sci-act', title: 'Vikas science experiment activity book', price: 60, supplier: 'Vikas' },
    { id: '7-eng-write', title: 'English (HL) Grammer and writing skills', price: 100, supplier: 'Navneet' },
    { id: '7-note', title: 'Single line 200 pg Long notebook - 11(A4 size)', price: 525, supplier: 'Navneet' },
    { id: '7-draw', title: '4A Jumbo Drawing book - Brown Colour', price: 52, supplier: 'Navneet' },
    { id: '7-diary', title: 'Diary & I Card', price: 170, supplier: 'Navneet' },
  ],
};

export const classOptions = [
  { value: '', label: 'Select class' },
  { value: '10th', label: 'Class 10' },
];

export const getFixedBookOptionsForClass = (cls: string): FixedBookOption[] => {
  return fixedBookOptionsByClass[cls] || [];
};
